### PR TITLE
Remove unwanted conditional compilation

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Sorry for forgetting to remove it. :-/

### CODE REVIEW

**Comment by raphlinus** [comment]
Still not working when I try `cargo publish`:

```
   Compiling pulldown-cmark v0.0.11 (file:///Users/raph/garden/pulldown-cmark/target/package/pulldown-cmark-0.0.11)
error[E0433]: failed to resolve. Could not find `Options` in `getopts`
   --> target/package/pulldown-cmark-0.0.11/src/main.rs:203:20
    |
203 |     let mut opts = getopts::Options::new();
    |                    ^^^^^^^^^^^^^^^^^^^^^ Could not find `Options` in `getopts`

error: use of unstable library feature 'rustc_private': use the crates.io `getopts` library instead (see issue #27812)
```

**Comment by GuillaumeGomez** [comment]
Arf! I think the binary will be built by default then. I'll update in this
way.

**Comment by GuillaumeGomez** [comment]
Should be okay now. Can you give it another try please?

**Comment by raphlinus** [comment]
Just `cargo publish` again? Getting the same failure.

**Comment by GuillaumeGomez** [comment]
Which version of cargo are you using?

**Comment by GuillaumeGomez** [comment]
Oh also, can you copy/paste the (full) output of the following command please:

```bash
cargo build --no-default-features
```

**Comment by raphlinus** [comment]
Sorry, git mistake on my end. Works now, and published as 0.0.11.

**Comment by GuillaumeGomez** [comment]
Pfiou. I feel relieved. Thanks!

**Pull request merged**
