### PR TITLE
Pass non normalized reference down

### PR DESCRIPTION
**Pull request by Manishearth**

### CODE REVIEW

**Comment by Manishearth** [comment]
We need both of these for this to work

**Comment by raphlinus** [comment]
Ah ok, wasn't sure.

I'm going to do an 0.1.2 which is technically a semver violation, but I think ok as there are no users of the 0.1.1 API.

**Comment by Manishearth** [comment]
You can just yank the version 😄

**Comment by raphlinus** [comment]
Done.

**Pull request merged**
