### PR TITLE
Initial table support.

### PR DESCRIPTION
**Pull request by notriddle**
This implements the table format used by [GitHub] and [MarkdownExtra]. It does not implement GitHub's alignment feature, but it can parse tables that have it; it just doesn't do anything with the alignment attributes.

[GitHub]: https://help.github.com/articles/github-flavored-markdown/#tables
[MarkdownExtra]: https://michelf.ca/projects/php-markdown/extra/#table

### CODE REVIEW

**Comment by notriddle** [comment]
Closes issue #7 .

**Comment by raphlinus** [comment]
Thanks for the PR! It looks like something we really need. Unfortunately I'm about to go on vacation and won't have access to my dev tools for a week. I'll review the PR when I get back, and if I don't, feel free to ping me.

**Comment by notriddle** [comment]
Thank you, also!

**Comment by notriddle** [comment]
Bump

**Comment by notriddle** [comment]
It's been over two weeks now. Could you please give some sort of response?

**Comment by raphlinus** [comment]
Many thanks!

**Comment by notriddle** [comment]
You're welcome!

**Pull request merged**
