### PR TITLE
Full html spec

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Sorry, only implemented part of the HTML spec in my last PR. This time it's complete.

### CODE REVIEW

**Comment by raphlinus** [comment]
Overall, I'm fine with these changes, but I do have one concern: it looks like you're editing `tests/spec.rs` by hand, where I believe this file is auto-generated from the spec (which itself is stored in `third_party/cmark`). I think it'd be fine if you moved the hand-written tests into a non-autogenerated file.

Feel free to correct me if I'm wrong about this, I didn't do the autogenerated spec tests myself.

**Comment by GuillaumeGomez** [comment]
I have no problem moving the new tests to another file. If `tests/spec.rs` is autogenerated, might be nice to say it in the header or somewhere. ;)

**Comment by GuillaumeGomez** [comment]
Ok, added a new file and moved my tests to this one.

**Comment by notriddle** [comment]
> tests/hmtl.rs

**Comment by GuillaumeGomez** [comment]
@notriddle: You haven't see anything. It's just between you and me.

**Comment by raphlinus** [comment]
Thanks!

**Comment by raphlinus** [comment]
Pushed 0.0.10 to crates.io at this commit.

**Pull request merged**
